name: Weekend FX Backfill

on:
  schedule:
    - cron: '10 0 * * 1'  # Every Monday at 00:10 UTC
  workflow_dispatch:

jobs:
  backfill-fx:
    runs-on: ubuntu-latest
    env:
      TRADERMADE_API_KEY: ${{ secrets.TRADERMADE_API_KEY }}
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install tradermade pandas requests

      - name: Run weekend FX backfill
        run: python backfill_fx_rates.py
